cli/login.go

If you quit the login flow, or don't actually login in your browser, the CLI still prints a message saying authentication was successful and that the configuration file was written.
This PR changes it so that this information is only printed if you're actually logged in and a configuration was actually written.

CLI login: don't print success message unless actually logged in

---

cli/run.go

This fixes a bug introduced in #9. We need to retry when the poll response is nil.

CLI run: fix panic on poll retry

---

cli/config.go
cli/run.go

The Dispatch SDK accepts three environment variables: https://github.com/stealthrocket/dispatch-py?tab=readme-ov-file#configuration.
The `dispatch run` command sets (overrides) two of them, `DISPATCH_API_KEY` and `DISPATCH_ENDPOINT_URL`, but passes on the third (`DISPATCH_VERIFICATION_KEY`) from the environment. A verification key is not required when using `dispatch run` because function calls are pulled from an authenticated endpoint of the Dispatch API.
This PR unsets `DISPATCH_VERIFICATION_KEY` before starting the local application, so that it doesn't conflict with the `dispatch run` session.
cc #8

Unset DISPATCH_VERIFICATION_KEY before running local application

---

cli/run.go

The intent of this change is to allow the Dispatch SDK to automatically discover the local endpoint that the CLI will be connecting to.

expose the local endpoint to the application as the DISPATCH_ENDPOINT_ADDR environment variable

---

cli/config.go
cli/login.go

This PR updates the CLI to store its configuration in `$XDG_CONFIG_HOME/dispatch/config.toml`, according to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). If `XDG_CONFIG_HOME` is not set, it defaults to `$HOME/.config`
For most users, this means that configuration will be stored at `$HOME/.config/dispatch/config.toml`
The `DISPATCH_CONFIG_PATH` override is still available, and takes precedence if set.

Respect XDG_CONFIG_HOME for configuration file

---

cli/config.go
cli/console.go
cli/switch.go

This PR reworks the configuration file:
* we print a warning comment at the beginning of the file letting the user know that the file is generated, and that it should not be edited directly
* we prefix organization configuration so that we can have configuration scoped to the CLI
* we hoist the `active` field out of the organization scope
Here's an example:
```toml
active = 'org1'
[Organizations]
[Organizations.org1]
api_key = 'foobar'
[Organizations.org2]
api_key = 'abcxyz'
```
It's not the prettiest looking thing, but this is what the TOML library we're using generates. I don't think we can improve it without using lower-level APIs or generating the file manually.
This fixes https://github.com/stealthrocket/dispatch/issues/5.

Rework the configuration file

---

cli/run.go

This reverts commit 4a79a0b39d7c1e692f63679142a63528a77eb6b1.
We now only strip `DISPATCH_VERIFICATION_KEY` from the environment.

Revert "Strip all env vars starting with DISPATCH_"

---

.gitignore
cli/run.go

There were some issues with Python's urllib and http.server modules when using IPv6.

default to use ipv4

---

cli/run.go

A minor improvement to avoid interleaving due to unbuffered writes to `os.Stderr`.

run: buffer line output

---

cli/run.go

This change will help with archaic HTTP servers that don't have proper support for reading chunked encoding in POST request bodies (e.g., Python `http.server.HTTPServer`).

run: always set content length

---

cli/run.go

A 404 can occur when sending a response or cleaning up a request if the request was removed upstream concurrently. This is expected when upstream load exceeds the ability for the local application to complete work. Upstream handles this gracefully; there's no need to print error messages in these cases.

Better handle 404's when interacting with Dispatch API

---

cli/tui.go

This PR updates the TUI to extract error details from the observed [`RunResponse`](https://github.com/dispatchrun/dispatch-proto/blob/b350ad1738d9eab96b78d21ea49ba04a08e7fcfc/dispatch/sdk/v1/function.proto#L77), and to prefer showing the error `type: message` over the status.
This fixes https://github.com/dispatchrun/dispatch/issues/29.
In the example from #29, the user would now see:
```
Function             Attempts   Duration Status                                                                                    
foo                         2     1.919s RuntimeError: oh no                                                                       
└─ bar                      1      475ms RuntimeError: oh no 
```
Previously they would see:
```
Function  Attempts   Duration Status
foo …
```

Show error info, if available

---

cli/tui.go

This PR updates the TUI to use unicode icons to represent whether a function call has succeeded, failed (permanently), or is still in-flight. The spinner that was shown previously has been removed.

tui: add icons in function call view

---

cli/run.go

We expect the local application to be a long-running server. If it exits early, it indicates a problem. We now dump the logs and print an error message in this case.
This can happen, for example, if the user is using the FastAPI integration, but runs their entry point script with `python` rather than an ASGI server like `uvicorn`.

Print a warning if the local application exits early

---

cli/run.go

The function call table shows the latest error that occurs, but if it's a temporary error the status is wiped as follow-up attempts are made. This PR adds the error type and message to the logs, so that you can see the same information in chronological form.

Show error type and message in the logs

---

cli/run.go
cli/run_linux.go

This PR contains a few fixes/tweaks to the headless (non-TUI) mode.
Firstly, it fixes a panic that occurs when `var tui *TUI` is nil. When it's cast to a `FunctionCallObserver`, the fact that it's `nil` isn't preserved, causing a panic when `if observer != nil { observer.ObserveRequest(...) }` is called.
Secondly, I've put the local application in a new process group, so that signals bound for the CLI aren't also received by the local application. This allows the CLI to handle/forward signals correctly, eliminating a race condition that can occur if the child sees the signal first and exits before the CLI has handled the same signal.
Finally, I've made it so that we unconditionally write a prefix before Dispatch and local application logs.

Fix headless mode

---

cli/tui.go

This PR adds a status bar to the function call view. For now, it just shows the total number of function calls, and the number of function calls still in-flight.
I've also tidied up the help bar, adding padding and removing the `t tail` help item unless the user is on the logs tab.
I initially tried to condense the status message and help into one line, but it looks weird. You either have to align the help to the right, which means you have to guess a fixed width, or use the terminal width and potentially have the help dangling way to the right. If you join the two with a separator but keep it aligned to the left it also looks weird because the help bar moves as the status message changes in size.

tui: add a status bar to function call view

---

cli/color.go
cli/config.go
cli/log.go
cli/run.go
cli/tui.go

This PR fixes a few issues with colors:
* we avoid using white, in case the user has a light/white background, instead using `lipgloss.NoColor` which is presumably white or black depending on the theme/background
* we use ANSI(256) colors now, and use a slightly darker shade of green/yellow/red that looks better on light and dark background
* we use lipgloss to style the log prefixes, and avoid manually parsing color related environment variables (which lipgloss does for us)
This fixes #31.

Color fixes

---

cli/error.go
cli/run.go
cli/tui.go

This fixes #43.
Instead of printing errors when an authentication error occurs, which conflicts with TUI rendering, we instead notify the TUI of the error so that it can render it on the status line.

tui: fix how auth errors are displayed in TUI mode

---

cli/run.go

This PR ensures we kill the child process if the CLI exits with an unexpected error.
[`Pdeathsig`](https://github.com/dispatchrun/dispatch/blob/aac1d73ff5f49721d724ae8fc63c798be0f0d140/cli/run_linux.go#L7) helps on Linux, but it isn't available elsewhere, e.g. macOS.
I've reworked how we create background goroutines so that if a panic occurs we manually kill the child process.

run: kill child process if CLI panics

---

cli/run.go
cli/style.go
go.mod
go.sum

This PR replaces the uuidv4 session IDs (e.g. `5dd1adcc-968f-4805-96a3-d551e0b7b986`) with a random 128-bit base62 string (e.g. `5KtjiELR4cK5pZDA89saUz`).

run: use base62 session IDs

---

cli/tui.go

This fixes an issue where one function call is sometimes truncated from the TUI.

tui: prevent one row from being truncated

---

cli/log.go
cli/run.go

This PR improves log messages. See the commits for details.

run: improve log output

---

cli/any.go
cli/python.go

The pickle library we're using ([gopickle](https://github.com/nlpodyssey/gopickle)) uses a `types.GenericClass` and `types.GenericObject` to represent custom classes and objects found in a pickle stream. For the common case where the class is a `@dataclass`, these types aren't sufficient; an error occurs when the pickle library tries to set `__dict__` properties, since `*types.GenericObject` doesn't implement `types.PyDictSettable`. This PR updates the formatter to instead use a custom generic object type which implements `PyDictSettable`. The result is that we can properly format data classes.
I've also updated the formatting layer to log more information when it encounters a Python value it can't parse.

run: improve formatting of Python input/output values

---

cli/run.go
cli/tui.go

This PR improves the error messages that the user sees when the local application can't be reached via the configurable `-e,--endpoint`, or it misbehaves in some way.
We now enrich error messages prior to notifying the TUI, and use shorter error messages.

run: improve error messages when local application can't be reached or misbehaves

---

cli/tui.go

When there are a lot of independent function calls with shallow call hierarchies, the extra table headers add a lot of unnecessary noise. This PR updates the functions view to show the table header only once, on the first function call table.

run: only show function table header once

---

cli/config.yaml
cli/login.go
cli/main.go
cli/style.go
cli/switch.go
cli/switch_test.go
go.mod
go.sum

Initial example of how dispatch could run the commands while redirecting stdout / stderr to make assertions. Might be useful for this issue https://github.com/dispatchrun/dispatch/issues/58. 
The global variables make running a bunch of unit tests in parallel more challenging, but if each CLI command takes in an "IO" interface with methods to read/write or make network calls then mocking,  running tests in parallel, and focusing on the logic rather than environment setup would be a lot easier.

test(unit): unit tests for switch command

---

.github/workflows/build.yml
Makefile
cli/run.go
cli/run_test.go

This PR adds initial integration tests for the `dispatch run` command

`dispatch run` integration tests

---

cli/run.go
cli/run_darwin.go
cli/run_default.go

Changes to signal handling:
* we spawn the child process in a new process group on macOS, like we were doing on Linux
* we forward whatever signal was first received, rather than unconditionally sending SIGTERM
* we forward the received signal to all processes in the process group
We're also now locking the OS thread before spawning the child process, to avoid issues with threads and `Pdeathsig` on Linux (this fixes https://github.com/dispatchrun/dispatch/issues/68).

run: fix signal handling

---

.github/workflows/build.yml
cli/run.go
cli/run_darwin.go
cli/run_default.go
cli/run_linux.go
cli/run_test.go
cli/run_windows.go

We should use something platform-independent instead of `printenv`. I'm going to work on this in another PR

Fix Windows build and build on Windows CI

---

.gitignore
.goreleaser.yml

Fixes #64 
@chriso is this enough? How can I test this locally?
I've tried to run `goreleaser release --snapshot --clean`, the output is:
```
➜ goreleaser release --snapshot --clean
• starting release...
• only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
• loading                                          path=.goreleaser.yml
• skipping announce, publish and validate...
• loading environment variables
• getting and validating git state
• git state                                      commit=5ba89d384d8067becde40b73714eff7db801e4ad branch=main current_tag=v0.2.0 previous_tag=v0.1.0 dirty=true
• pipe skipped                                   reason=disabled during snapshot mode
• parsing tag
• setting defaults
• snapshotting
• …
```

Show correct version

---

cli/switch_test.go

This imports both lipgloss and termenv, and then uses `SetColorProfile()` to use `termenv.Ascii` which has no-color. I placed this within the setupConfig so it applies to all tests that end up calling the `setupConfig()`. It could also be moved to directly within `TestSwitchCommand()`. I'm not sure which you would prefer.
This fixes Issue #66.

Fixes #66 by forcing lipgloss to have no color output

---

cli/init.go
cli/init_test.go
cli/main.go
cli/main_test.go

This PR implements `dispatch init` command to initialize a new project.
```sh
dispatch init <template> [path]
```
Where `<template>` is a required option and `[path]` is optional.
On a first use the command will create an Application Data directory `dispatch`
- **Windows**: The application data directory is typically located at `%APPDATA%` or `%LOCALAPPDATA%`.
- **macOS**: The application data directory is typically located at `$HOME/Library/Application Support`.
- **Linux**: The application data directory is typically located at `$XDG_CONFIG_HOME or $HOME/.config`.
The App Data directory is used to save templates oh a user's computer to make them available for use later without Internet.
The directory has follows structure:
```
dispatch/
templates/
foo/
bar/
templates.sha
```
1) …

add `dispatch init` command

---

cli/init.go
cli/init_test.go

This code patches the first line of the `go.mod` file to set a module name to a directory name.

Give Go module initialized with `dispatch init` the same name as it's directory name

---

.goreleaser.yml

~~This should just work?~~ It works.  I've tested it with `goreleaser --snapshot` and ran on my Windows laptop
part of the #83

Windows build
